### ISSUE TITLE
Allow housing to be assigned within the registration system

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#177]
Instead of doing it in an external spreadsheet, make the system be aware of what spaces are available and what are taken.

**Comment by NullVoxPopuli** [comment]
This will tie-in with some of the other housing to-dos, but I'm thinking this: (and this is more for me, so I don't forget for when I get around to implementing)

New Objects:
  * HousingProvisions - Do not require an Attendance, but an Attendance can create them. These are what will store how mane spaces are available at what location, and if travel options are available.
  * HousingRequest - Tied to an Attendance, but are not required to be tied to an Attendance (like in the case of band / instructors). These will be assigned to a HousingProvision, and can have RequestedRoommates, and UnwantedRoommates, as well as the typical, allergy and note information that is collected today.

Total spaces available will be a dynamic number calculated by the summing all the spaces available from all the housing provisions.

I can make this behave so that at any given point in time, the event manager can say that there must an available spot in the housing provisions before a housing request can be made. 

and / or; housing requests will be marked as wait-listed until an available space is created - at which point, the attendee associated with the housing request will get an automated email saying there is now space for them.

It may also be advantageous to have a setting on the event to say not to waitlist people until so many housing requests have been made. This means that the event organizer is responsible for achieving the amount of housing slots specified by this new setting.  This should probably go in to the terms of service.

I probably need to update the ToS anyway...

Anywho, anything seems out of place?

**Comment by bradke** [comment]
I like the provision of the last paragraph...because you know the 10 spaces that people immediately offered up won't be sufficient and we will go begging for more lol

**Comment by NullVoxPopuli** [comment]
Provision and Requests are implemented and soon to be released. The bit where the wait list notifications are sent out will be done later (the important part is just collecting all the needed data from the beginning)

**Comment by bradke** [comment]
Other thoughts as I'm assigning housing:
-Within the system, be able to go to the HousingRequest and by drop-down, be able to assign an Attendance to a HousingProvision (of course, having side-by-side lists and being able to click-drag assignments would be pretty cool, but I'm guessing that's a more time consuming UI to write)
-Obviously, have the ability to unlink this assignment at any time so it can be rearranged
-Have a warning/notice pop-up anytime an allergy or unwanted roommate violation happens, with the ability to ignore the pop-up and continue with assignment, or go back and make a different assignment
-Prevent too many Attendances from being assigned to a HousingProvision

**Comment by NullVoxPopuli** [comment]
@bradke I can do some of this after our checkin dry-run this Monday.
Particularly:

> -Within the system, be able to go to the HousingRequest and by drop-down, be able to assign an Attendance to a HousingProvision
> -Prevent too many Attendances from being assigned to a HousingProvision

not sure how close I'd got to side by side lists, but lets see what happens!

> -Obviously, have the ability to unlink this assignment at any time so it can be rearranged

ez

> -Have a warning/notice pop-up anytime an allergy or unwanted roommate violation happens, with the ability to ignore the pop-up and continue with assignment, or go back and make a different assignment

Not sure I'll get to this totally being automatic, but at least the logic isn't hard. :-)
