### ISSUE TITLE
ensure only students use the student discount

### ISSUE THREAD

**Issue by bradke** [NullVoxPopuli/aeonvera#236]
when someone sets up an account or registers for an event, the system should only allow people that register with .edu email addresses to use the student discount

**Comment by NullVoxPopuli** [comment]
that is a good idea!

**Comment by NullVoxPopuli** [comment]
@bradke what if someone doesn't want to use their school email?
the logic of this could get kinda wonky - especially if there is a student discount code simultaneously in play.

**Comment by bradke** [comment]
Hmmm, true. And some people get to keep their .edu address as an alumni. I dunno, I subscribe to other sites that require the use of my edu for a discount. I don't have a problem with forcing it, but if it's too complicated, nbd. 

Brittany

**Comment by NullVoxPopuli** [comment]
I just see that there would either be double discounts, or people would be
annoyed that they have to switch their email to an .edu.

maybe what we could do, is have them enter an edu email in order to verify
that they are a student.
discount wouldn't be applied until the clicked the confirmation link sent
to their edu email?

**Comment by bradke** [comment]
That works as well!

Brittany
